version: "0.1"
services:
  neo4j:
    container_name: "taskscore-neo4j"
    build: ./neo4j
    ports:
      - "7687:7687"
    environment:
      - NEO4JLABS_PLUGINS='["apoc"]'
      - dbms.directories.import="/"
    volumes:
      - $HOME/neo4j/data:/data
    healthcheck:
        test: netstat -ltn | grep -c 7687
        interval: 8s
        timeout: 10s
        retries: 5

  app:
    container_name: "taskscore-app"
    build: ./app
    depends_on:
      neo4j:
        condition: service_healthy

  swagger: 
    container_name: "taskscore-swagger"
    image: "swaggerapi/swagger-ui"
    environment:
      - BASE_URL=/swagger
      - SWAGGER_JSON_URL=${SWAGGER_PROTOCOL}://${PROXY_HOST}:${SWAGGER_PORT}/rest/openapi.json
    depends_on:
      - app

  nginx:
    container_name: "taskscore-nginx"
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - app
      - swagger
    
